baseurl = "https://www.nedrockson.com/"
languageCode = "en-us"
theme = "hugo-ink"

title = "Compiling Leadership"
relativeurls = false
paginate = 5

copyright = "© 2019 Ned Rockson. Some Rights Reserved"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-89702408-1"

[params]
    subtitle = "15 years of building, leading, and managing; failures and successes"

    mode = "auto"

# Nav links below the profile picture
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[paras.social]]
name = "Github"
icon = "github"
url = "https://github.com/nedrocks"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nedrockson"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/nedrocks"

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
unsafe= true